changelog:
    categories:
        - title: New Features 🎉
          labels:
              - Semver-Minor
              - enhancement
        - title: Notable Changes 🛠
          labels:
              - Semver-Major
              - breaking-change
        - title: Known bugs
          labels:
              - "*"
